swagger: '2.0'
info:
  title: My API
  version: "1.0.0"
host: api.mysite.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /customers:
    get:
      description: Get list of customers.
      operationId: listCustomers
      responses:
        200:
          description: List of customers
          schema:
            type: array
            items:
              $ref: '#/definitions/Customer'
    post:
      description: Create a customer
      operationId: createCustomer
      parameters:
        - name: customer
          in: body
          schema:
            $ref: '#/definitions/NewCustomer'
      responses:
        201:
          description: Customer
          schema:
            $ref: '#/definitions/Customer'
  /customers/{customerId}:
    get:
      description: Get a customer by id
      operationId: getCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Customer
          schema:
            $ref: '#/definitions/Customer'

definitions:
  NewCustomer:
    properties:
      name:
        type: string
      tag:
        type: string

  Customer:
    properties:
      id:
        type: string
      href:
        type: string
      name:
        type: string
      tag:
        type: string
