swagger: '2.0'
info:
  title: My API
  version: 1.0.0
host: api.mysite.com
schemes:
  - https
basePath: /v1
produces:
  - application/json

paths:
  /customers:
    get:
      description: Get list of customers.
      responses:
        '200':
          description: List of customers
          schema:
            type: array
            items:
              $ref: '#/definitions/Customer'
    post:
      description: Create a customer
      parameters:
        - name: customer
          in: body
          schema:
            $ref: '#/definitions/Customer'
      responses:
        '201':
          description: Customer
          schema:
            $ref: '#/definitions/Customer'

  /customers/{id}:
    get:
      description: Get a customer by id
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Customer
          schema:
            $ref: '#/definitions/Customer'

definitions:
  Customer:
    properties:
      id:
        type: string
      name:
        type: string
      gold:
        type: boolean
      joined:
        type: string
        format: date
