swagger: '2.0'
info:
  title: My API
  version: 1.0.0
host: api.mysite.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
securityDefinitions:
  auth:
    type: oauth2
    authorizationUrl: 'https://api.mysite.com/account/authenticate'
    flow: implicit
security:
  - auth: []
paths:
  /customers:
    get:
      parameters:
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/limit'
      tags:
        - public
      description: Get list of customers.
      operationId: listCustomers
      responses:
        '200':
          description: List of customers
          schema:
            type: array
            items:
              $ref: '#/definitions/CustomerSummary'
    post:
      tags:
        - public
      description: Create a customer
      operationId: createCustomer
      parameters:
        - name: customer
          in: body
          schema:
            $ref: '#/definitions/CustomerCreate'
      responses:
        '201':
          description: Customer
          schema:
            $ref: '#/definitions/CustomerDetail'
  /customers/{customerId}:
    get:
      tags:
        - public
      description: Get a customer by id
      operationId: getCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Customer
          schema:
            $ref: '#/definitions/CustomerDetail'
          examples:
            application/json:
              id: abc123
              href: 'https://api.mysite.com/v1/customers/abc123'
              name: Customer Ltd
              gold: true
              joined: '2015-09-11'
    delete:
      tags:
        - public
      description: Delete customer by id
      parameters:
        - name: customerId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Customer was deleted
        404:
          description: Customer wasn't found

parameters:
  offset:
    name: offset
    in: query
    description: number of items to skip
    type: integer
    format: int32
  limit:
    name: limit
    in: query
    description: max items to return
    type: integer
    format: int32
definitions:
  CustomerCreate:
    properties:
      name:
        type: string
      gold:
        type: boolean
  CustomerSummary:
    properties:
      id:
        type: string
      href:
        type: string
      name:
        type: string
  CustomerDetail:
    allOf:
    - $ref: '#/definitions/CustomerSummary'
    - properties:
        gold:
          type: boolean
        joined:
          type: string
          format: date
